name: Python CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install flake8 black pytest

      - name: Run linter (flake8)
        run: flake8 .

      - name: Run formatter check (black)
        run: black --check .

      - name: test_main.py
        run: pytest


