name: welcome pipeline

on:
  push:
    branches:
      - main

jobs:
  welcome-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Say Welcome
        run: echo "welcome Ahmad code pushed to main."
